services:
  - type: web
    name: performa-roles-abrantes
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    nodeVersion: 22.14.0
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_ENV
        value: production