services:
  - type: web
    name: performa-roles-abrantes
    env: node
    buildCommand: yarn install && yarn add terser --dev && yarn build
    startCommand: yarn start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; connect-src 'self' https://*.supabase.co; img-src 'self' data: https://*.supabase.co; style-src 'self' 'unsafe-inline'; script-src 'self';"
      - path: /*
        name: X-Frame-Options
        value: DENY
    domains:
      - abrantes.vivacomdev.com