services:
  - type: web
    name: performa-roles-abrantes
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production