services:
  - type: web
    name: performa-roles-abrantes
    env: node
    buildCommand: |
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun install
      bun build ./src/main.tsx --outdir=dist
    startCommand: |
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun run start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production