services:
  - type: web
    name: performa-roles-abrantes
    env: node
    buildCommand: curl -fsSL https://bun.sh/install | bash && $HOME/.bun/bin/bun install && $HOME/.bun/bin/bun run build
    startCommand: $HOME/.bun/bin/bun run start
    nodeVersion: 22.14.0
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_ENV
        value: production