// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqvonmobyoxbntddvfew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdm9ubW9ieW94Ym50ZGR2ZmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzOTg4NDMsImV4cCI6MjA1NTk3NDg0M30.ljfcpEykffNwydfFnh29PjArFz9TecPAs8-PGnv5R8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);